volumes:
  roop-data:

services:
  app:
    build: .
    image: roop-unleashed
    ports:
      - "7860:7860"
    volumes:
      - roop-data:/app/models
      - $PWD/config.yaml:/app/config.yaml
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute, utility]
